[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
rcgen = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
